import pylabwons as lw


BASELINE = SCHEMA = lw.DataDictionary(
    name=lw.DataDictionary(
        kor_name='종목명',
        rel_name='종목명',
        rel_group='',
        rel_width=19,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    market=lw.DataDictionary(
        kor_name='시장',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    sectorCode=lw.DataDictionary(
        kor_name='섹터코드',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    sectorName=lw.DataDictionary(
        kor_name='섹터분류',
        rel_name='섹터분류',
        rel_group='',
        rel_width=14,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    industryCode=lw.DataDictionary(
        kor_name='업종코드',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    industryName=lw.DataDictionary(
        kor_name='업종분류',
        rel_name='업종분류',
        rel_group='',
        rel_width=10.4,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    tradingDate=lw.DataDictionary(
        kor_name='거래일',
        rel_name='거래일',
        rel_group='',
        rel_width=9,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    marketCap=lw.DataDictionary(
        kor_name='시가총액',
        rel_name='시가총액',
        rel_group='',
        rel_width=10.38,
        ref='한국거래소',
        calc='',
        unit='원',
        data_type=int,
        round=0,
    ),
    close=lw.DataDictionary(
        kor_name='종가',
        rel_name='종가',
        rel_group='',
        rel_width=8,
        ref='한국거래소',
        calc='',
        unit='원',
        data_type=int,
        round=0,
    ),
    volume=lw.DataDictionary(
        kor_name='거래량',
        rel_name='거래량',
        rel_group='',
        rel_width=9,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    amount=lw.DataDictionary(
        kor_name='거래대금',
        rel_name='거래대금',
        rel_group='',
        rel_width=12,
        ref='한국거래소',
        calc='',
        unit='원',
        data_type=int,
        round=0,
    ),
    returnOn1Day=lw.DataDictionary(
        kor_name='1일 수익률',
        rel_name='1일 수익률',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (직전 거래일 종가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    returnOn1Week=lw.DataDictionary(
        kor_name='1주 수익률',
        rel_name='1주 수익률',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (5 거래일 전 종가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    returnOn1Month=lw.DataDictionary(
        kor_name='1개월 수익률',
        rel_name='1개월 수익률',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (21 거래일 전 종가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    returnOn3Months=lw.DataDictionary(
        kor_name='3개월 수익률',
        rel_name='3개월 수익률',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (63 거래일 전 종가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    returnOn6Months=lw.DataDictionary(
        kor_name='6개월 수익률',
        rel_name='6개월 수익률',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (126 거래일 전 종가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    returnOn1Year=lw.DataDictionary(
        kor_name='1년 수익률',
        rel_name='1년 수익률',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (252 거래일 전 종가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiftyTwoWeekHigh=lw.DataDictionary(
        kor_name='52주 최고가',
        rel_name='52주 최고가',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='52주 내 종가 중 최고가',
        unit='원',
        data_type=int,
        round=0,
    ),
    fiftyTwoWeekLow=lw.DataDictionary(
        kor_name='52주 최저가',
        rel_name='52주 최저가',
        rel_group='',
        rel_width=11,
        ref='한국거래소, 별도 계산',
        calc='52주 내 종가 중 최저가',
        unit='원',
        data_type=int,
        round=0,
    ),
    fiftyTwoWeekHighPct=lw.DataDictionary(
        kor_name='52주 최고가 대비',
        rel_name='52주 최고가 대비',
        rel_group='',
        rel_width=12.4,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (52주 최고가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiftyTwoWeekLowPct=lw.DataDictionary(
        kor_name='52주 최저가 대비',
        rel_name='52주 최저가 대비',
        rel_group='',
        rel_width=12.4,
        ref='한국거래소, 별도 계산',
        calc='(최근 거래일 종가) / (52주 최저가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),

    shares=lw.DataDictionary(
        kor_name='상장 주식수(최근 분기)',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    sharesOutstanding=lw.DataDictionary(
        kor_name='상장 주식수',
        rel_name='상장 주식수',
        rel_group='',
        rel_width=12,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    sharesPreferred=lw.DataDictionary(
        kor_name='우선주',
        rel_name='우선주',
        rel_group='',
        rel_width=9,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    sharesFloating=lw.DataDictionary(
        kor_name='유동 주식수',
        rel_name='유동 주식수',
        rel_group='',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    sharesFloatingRate=lw.DataDictionary(
        kor_name='유동 주식비율',
        rel_name='유동 주식비율',
        rel_group='',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    foreignSharesHolding=lw.DataDictionary(
        kor_name='외국인 보유수량',
        rel_name='외국인 보유수량',
        rel_group='',
        rel_width=12,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    foreignRate=lw.DataDictionary(
        kor_name='외국인 보유비율',
        rel_name='외국인 보유비율',
        rel_group='',
        rel_width=11,
        ref='한국거래소',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    foreignSharesLimit=lw.DataDictionary(
        kor_name='외국인 한도수량',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    foreignRateByLimit=lw.DataDictionary(
        kor_name='외국인 한도소진율',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),

    numbersDate=lw.DataDictionary(
        kor_name='공시자료 수집일',
        rel_name='공시자료 수집일',
        rel_group='',
        rel_width=12,
        ref='',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),

    trailingRevenue=lw.DataDictionary(
        kor_name='매출(4분기 합산)',
        rel_name='매출',
        rel_group='4분기 합산',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='최근 4개 분기 발표 실적 매출의 합',
        unit='억원',
        data_type=int,
        round=0,
    ),
    trailingProfit=lw.DataDictionary(
        kor_name='영업이익(4분기 합산)',
        rel_name='영업이익',
        rel_group='4분기 합산',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='최근 4개 분기 발표 실적 영업이익의 합',
        unit='억원',
        data_type=int,
        round=0,
    ),
    trailingNetProfit=lw.DataDictionary(
        kor_name='당기순이익(4분기 합산)',
        rel_name='당기순이익',
        rel_group='4분기 합산',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='최근 4개 분기 발표 실적 당기순이익의 합',
        unit='억원',
        data_type=int,
        round=0,
    ),
    trailingProfitRate=lw.DataDictionary(
        kor_name='영업이익률(4분기 합산)',
        rel_name='영업이익률',
        rel_group='4분기 합산',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 4개 분기 발표 실적 영업이익의 합) / (최근 4개 분기 발표 실적 매출의 합)',
        unit='%',
        data_type=float,
        round=2,
    ),
    trailingEps=lw.DataDictionary(
        kor_name='EPS(4분기 합산)',
        rel_name='EPS',
        rel_group='4분기 합산',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='최근 4개 분기 발표 실적 EPS의 합',
        unit='원',
        data_type=float,
        round=2,
    ),
    trailingPs=lw.DataDictionary(
        kor_name='PSR(4분기 합산)',
        rel_name='PSR',
        rel_group='4분기 합산',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 거래일 시가총액) / (최근 4개 분기 발표 실적 매출의 합)',
        unit='',
        data_type=float,
        round=2,
    ),
    trailingPe=lw.DataDictionary(
        kor_name='PER(4분기 합산)',
        rel_name='PER',
        rel_group='4분기 합산',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 거래일 종가) / (최근 4개 분기 발표 실적 EPS의 합)',
        unit='',
        data_type=float,
        round=2,
    ),
    trailingPeg=lw.DataDictionary(
        kor_name='PEG(4분기 합산)',
        rel_name='PEG(확정 실적 기반)',
        rel_group='4분기 합산',
        rel_width=13.5,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 4분기 발표 실적 기준 PER) / (최근 분기 발표 실적 전년도 동기 대비 EPS 성장률)',
        unit='',
        data_type=float,
        round=2,
    ),

    yoyRevenue=lw.DataDictionary(
        kor_name='매출(전년 동기 대비)',
        rel_name='매출',
        rel_group='전년 동기 대비',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 분기 발표 매출) / (전년 동기 발표 매출) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    yoyProfit=lw.DataDictionary(
        kor_name='영업이익(전년 동기 대비)',
        rel_name='영업이익',
        rel_group='전년 동기 대비',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 분기 발표 영업이익) / (전년 동기 발표 영업이익) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    yoyNetProfit=lw.DataDictionary(
        kor_name='당기순이익(전년 동기 대비)',
        rel_name='당기순이익',
        rel_group='전년 동기 대비',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 분기 발표 당기순이익) / (전년 동기 발표 당기순이익) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    yoyProfitRate=lw.DataDictionary(
        kor_name='영업이익률(전년 동기 대비)',
        rel_name='영업이익률',
        rel_group='전년 동기 대비',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 분기 발표 영업이익률) / (전년 동기 발표 영업이익률) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    yoyEps=lw.DataDictionary(
        kor_name='EPS(전년 동기 대비)',
        rel_name='EPS',
        rel_group='전년 동기 대비',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 분기 발표 EPS) / (전년 동기 발표 EPS) - 1',
        unit='%',
        data_type=str,
        round=2,
    ),

    fiscalMonth=lw.DataDictionary(
        kor_name='확정 실적 기준',
        rel_name='기준일',
        rel_group='직전 결산 기준',
        rel_width=10.25,
        ref='에프앤가이드',
        calc='',
        unit='년/월',
        data_type=str,
        round=0,
    ),
    ifrsType=lw.DataDictionary(
        kor_name='IFRS재무기준',
        rel_name='IFRS재무기준',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    fiscalRevenue=lw.DataDictionary(
        kor_name='매출(직전결산연도)',
        rel_name='매출',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    fiscalRevenueGrowth=lw.DataDictionary(
        kor_name='매출성장률(직전결산연도)',
        rel_name='매출성장률',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 매출) / (전년 결산연도 매출) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalProfit=lw.DataDictionary(
        kor_name='영업이익(직전결산연도)',
        rel_name='영업이익',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    fiscalProfitGrowth=lw.DataDictionary(
        kor_name='영업이익성장률(직전결산연도)',
        rel_name='영업이익성장률',
        rel_group='직전 결산 기준',
        rel_width=10.5,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 영업이익) / (전년 결산연도 영업이익) - 1',
        unit='%',
        data_type=str,
        round=2,
    ),
    fiscalProfitRate=lw.DataDictionary(
        kor_name='영업이익률(직전결산연도)',
        rel_name='영업이익률',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalProfitRateGrowth=lw.DataDictionary(
        kor_name='영업이익률 성장률(직전결산연도)',
        rel_name='영업이익률 성장률',
        rel_group='직전 결산 기준',
        rel_width=12,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 영업이익률) / (전년 결산연도 영업이익률) - 1',
        unit='%',
        data_type=str,
        round=2,
    ),
    fiscalNetProfit=lw.DataDictionary(
        kor_name='당기순이익(직전결산연도)',
        rel_name='당기순이익',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    fiscalNetProfitGrowth=lw.DataDictionary(
        kor_name='당기순이익성장률(직전결산연도)',
        rel_name='당기순이익성장률',
        rel_group='직전 결산 기준',
        rel_width=12,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 당기순이익) / (전년 결산연도 당기순이익) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalAsset=lw.DataDictionary(
        kor_name='자산(직전결산연도)',
        rel_name='자산',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    fiscalAssetGrowth=lw.DataDictionary(
        kor_name='자산증감률(직전결산연도)',
        rel_name='자산증감률',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 자산) / (전년 결산연도 자산) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalCapital=lw.DataDictionary(
        kor_name='자본(직전결산연도)',
        rel_name='자본',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    fiscalDebt=lw.DataDictionary(
        kor_name='부채(직전결산연도)',
        rel_name='부채',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    fiscalDebtGrowth=lw.DataDictionary(
        kor_name='부채증감률(직전결산연도)',
        rel_name='부채증감률',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 부채) / (전년 결산연도 부채) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalDebtRatio=lw.DataDictionary(
        kor_name='부채율(직전결산연도)',
        rel_name='부채율',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalRetentionRate=lw.DataDictionary(
        kor_name='유보율(직전결산연도)',
        rel_name='유보율',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalDividendYield=lw.DataDictionary(
        kor_name='배당수익률(직전결산연도)',
        rel_name='배당수익률',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalPayoutRatio=lw.DataDictionary(
        kor_name='배당성향(직전결산연도)',
        rel_name='배당성향',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(발행 주식 수) x (최근 결산연도 DPS) / (최근 결산연도 당기순이익)',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalPayoutRatioGrowth=lw.DataDictionary(
        kor_name='배당성향증감률(직전결산연도)',
        rel_name='배당성향증감률',
        rel_group='직전 결산 기준',
        rel_width=11,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 배당성향) / (전년 결산연도 배당성향) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    returnOnAsset=lw.DataDictionary(
        kor_name='ROA(직전결산연도)',
        rel_name='ROA',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    returnOnEquity=lw.DataDictionary(
        kor_name='ROE(직전결산연도)',
        rel_name='ROE',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalEps=lw.DataDictionary(
        kor_name='EPS(직전결산연도)',
        rel_name='EPS',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='원',
        data_type=float,
        round=2,
    ),
    fiscalEpsGrowth=lw.DataDictionary(
        kor_name='EPS성장률(직전결산연도)',
        rel_name='EPS성장률',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 EPS) / (전년 결산연도 EPS) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    fiscalPe=lw.DataDictionary(
        kor_name='PER(직전결산연도)',
        rel_name='PER',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=float,
        round=2,
    ),
    fiscalPriceToBook=lw.DataDictionary(
        kor_name='PBR(직전결산연도)',
        rel_name='PBR',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=float,
        round=2,
    ),
    fiscalDps=lw.DataDictionary(
        kor_name='DPS(직전결산연도)',
        rel_name='DPS',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='원',
        data_type=float,
        round=2,
    ),
    fiscalDpsGrowth=lw.DataDictionary(
        kor_name='DPS증감률(직전결산연도)',
        rel_name='DPS증감률',
        rel_group='직전 결산 기준',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 결산연도 DPS) / (전년 결산연도 DPS) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    estimation=lw.DataDictionary(
        kor_name='컨센서스',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=float,
        round=2,
    ),
    estimatedMonth=lw.DataDictionary(
        kor_name='추정 기준일',
        rel_name='기준일',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=str,
        round=2,
    ),
    targetPrice=lw.DataDictionary(
        kor_name='목표가',
        rel_name='목표가',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='원',
        data_type=float,
        round=2,
    ),
    targetPricePct=lw.DataDictionary(
        kor_name='목표가대비',
        rel_name='목표가대비',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(최근 거래일 종가) / (목표가) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    nOfEstimations=lw.DataDictionary(
        kor_name='추정기관수',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=float,
        round=2,
    ),
    estimatedRevenue=lw.DataDictionary(
        kor_name='매출(추정)',
        rel_name='매출',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    estimatedRevenueGrowth=lw.DataDictionary(
        kor_name='매출성장률(추정)',
        rel_name='매출성장률',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 매출) / (최근 결산연도 매출) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),

    estimatedProfit=lw.DataDictionary(
        kor_name='영업이익(추정)',
        rel_name='영업이익',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    estimatedProfitRate=lw.DataDictionary(
        kor_name='영업이익률(추정)',
        rel_name='영업이익률',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='%',
        data_type=float,
        round=2,
    ),
    estimatedProfitGrowth=lw.DataDictionary(
        kor_name='영업이익성장률(추정)',
        rel_name='영업이익성장률',
        rel_group='컨센서스',
        rel_width=10.5,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 영업이익) / (최근 결산연도 영업이익) - 1',
        unit='%',
        data_type=str,
        round=2,
    ),
    estimatedProfitRateGrowth=lw.DataDictionary(
        kor_name='영업이익률 성장률(추정)',
        rel_name='영업이익률 성장률',
        rel_group='컨센서스',
        rel_width=12,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 영업이익률) / (최근 결산연도 영업이익률) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    estimatedNetProfit=lw.DataDictionary(
        kor_name='당기순이익(추정)',
        rel_name='당기순이익',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    estimatedNetProfitGrowth=lw.DataDictionary(
        kor_name='당기순이익성장률(추정)',
        rel_name='당기순이익성장률',
        rel_group='컨센서스',
        rel_width=12,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 당기순이익) / (최근 결산연도 당기순이익) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),

    estimatedAsset=lw.DataDictionary(
        kor_name='자산(추정)',
        rel_name='자산',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    estimatedAssetGrowth=lw.DataDictionary(
        kor_name='자산증감률(추정)',
        rel_name='자산증감률',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 자산) / (최근 결산연도 자산) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    estimatedDebt=lw.DataDictionary(
        kor_name='부채(추정)',
        rel_name='부채',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='억원',
        data_type=int,
        round=0,
    ),
    estimatedDebtGrowth=lw.DataDictionary(
        kor_name='부채증감률(추정)',
        rel_name='부채증감률',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 부채) / (최근 결산연도 부채) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    estimatedEps=lw.DataDictionary(
        kor_name='EPS(추정)',
        rel_name='EPS',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='원',
        data_type=float,
        round=2,
    ),
    estimatedEpsGrowth=lw.DataDictionary(
        kor_name='EPS성장률(추정)',
        rel_name='EPS성장률',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 EPS) / (최근 결산연도 EPS) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    estimatedPe=lw.DataDictionary(
        kor_name='PER(추정)',
        rel_name='PER',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=float,
        round=2,
    ),
    forwardEps=lw.DataDictionary(
        kor_name='EPS(12개월선행)',
        rel_name='EPS(12개월선행)',
        rel_group='컨센서스',
        rel_width=13.5,
        ref='에프앤가이드',
        calc='',
        unit='원',
        data_type=float,
        round=2,
    ),
    forwardPe=lw.DataDictionary(
        kor_name='PER(12개월선행)',
        rel_name='PER(12개월선행)',
        rel_group='컨센서스',
        rel_width=13.5,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=float,
        round=2,
    ),
    forwardPeg=lw.DataDictionary(
        kor_name='PEG(12개월선행)',
        rel_name='PEG(12개월선행)',
        rel_group='컨센서스',
        rel_width=13.5,
        ref='에프앤가이드, 별도 계산',
        calc='(12개월 선행 PER) / (추정 EPS 성장률) - 1',
        unit='',
        data_type=float,
        round=2,
    ),
    estimatedDps=lw.DataDictionary(
        kor_name='DPS(추정)',
        rel_name='DPS',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='원',
        data_type=float,
        round=2,
    ),
    estimatedDpsGrowth=lw.DataDictionary(
        kor_name='DPS성장률(추정)',
        rel_name='DPS성장률',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 DPS) / (최근 결산연도 DPS) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),
    estimatedPayoutRatio=lw.DataDictionary(
        kor_name='배당성향(추정)',
        rel_name='배당성향',
        rel_group='컨센서스',
        rel_width=10,
        ref='에프앤가이드, 별도 계산',
        calc='(상장주식수) x (추정 DPS) / (추정 당기순이익)',
        unit='',
        data_type=float,
        round=2,
    ),
    estimatedPayoutRatioGrowth=lw.DataDictionary(
        kor_name='배당성향증감률(추정)',
        rel_name='배당성향증감률',
        rel_group='컨센서스',
        rel_width=11,
        ref='에프앤가이드, 별도 계산',
        calc='(추정 배당성향 / (최근 결산연도 배당성향) - 1',
        unit='%',
        data_type=float,
        round=2,
    ),

    wicsDate=lw.DataDictionary(
        kor_name='WICS기준일',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),
    groupByMarketCap=lw.DataDictionary(
        kor_name='추종지수(대형주)',
        rel_name='',
        rel_group='',
        rel_width=10,
        ref='',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    industryNameKrx=lw.DataDictionary(
        kor_name='KRX업종분류',
        rel_name='KRX업종분류',
        rel_group='기타',
        rel_width=20,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    industryPe=lw.DataDictionary(
        kor_name='KRX업종PER',
        rel_name='KRX업종PER',
        rel_group='기타',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=float,
        round=2,
    ),
    products=lw.DataDictionary(
        kor_name='주요제품',
        rel_name='주요제품',
        rel_group='기타',
        rel_width=16,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=str,
        round=0,
    ),
    ipo=lw.DataDictionary(
        kor_name='상장일',
        rel_name='상장일',
        rel_group='기타',
        rel_width=10,
        ref='한국거래소',
        calc='',
        unit='',
        data_type=int,
        round=0,
    ),

    beta=lw.DataDictionary(
        kor_name='베타',
        rel_name='베타',
        rel_group='기타',
        rel_width=10,
        ref='에프앤가이드',
        calc='',
        unit='',
        data_type=float,
        round=3,
    ),
)
