import pylabwons as lw


BASELINE = lw.DataDictionary(
    name=lw.DataDictionary(
        kor_name='종목명',
        data_type=str,
    ),
    market=lw.DataDictionary(
        kor_name='시장',
        data_type=str,
    ),
    tradingDate=lw.DataDictionary(
        kor_name='거래일',
        data_type=int,
    ),
    marketCap=lw.DataDictionary(
        kor_name='시가총액',
        data_type=int,
    ),
    close=lw.DataDictionary(
        kor_name='종가',
        data_type=int,
    ),
    volume=lw.DataDictionary(
        kor_name='거래량',
        data_type=int,
    ),
    amount=lw.DataDictionary(
        kor_name='거래대금',
        data_type=int,
    ),
    returnOn1Day=lw.DataDictionary(
        kor_name='1일수익률',
        data_type=float,
    ),
    returnOn1Week=lw.DataDictionary(
        kor_name='1주수익률',
        data_type=float,
    ),
    returnOn1Month=lw.DataDictionary(
        kor_name='1개월수익률',
        data_type=float,
    ),
    returnOn3Months=lw.DataDictionary(
        kor_name='3개월수익률',
        data_type=float,
    ),
    returnOn6Months=lw.DataDictionary(
        kor_name='6개월수익률',
        data_type=float,
    ),
    returnOn1Year=lw.DataDictionary(
        kor_name='1년수익률',
        data_type=float,
    ),
    fiftyTwoWeekHigh=lw.DataDictionary(
        kor_name='52주최고가',
        data_type=float,
    ),
    fiftyTwoWeekLow=lw.DataDictionary(
        kor_name='52주최저가',
        data_type=float,
    ),
    fiftyTwoWeekHighPct=lw.DataDictionary(
        kor_name='52주최고가대비',
        data_type=float,
    ),
    fiftyTwoWeekLowPct=lw.DataDictionary(
        kor_name='52주최저가대비',
        data_type=float,
    ),

    shares=lw.DataDictionary(
        kor_name='상장주식수(최근분기)',
        data_type=int,
    ),
    sharesOutstanding=lw.DataDictionary(
        kor_name='상장주식수',
        data_type=int,
    ),
    sharesPreferred=lw.DataDictionary(
        kor_name='우선주',
        data_type=int,
    ),
    sharesFloating=lw.DataDictionary(
        kor_name='유동주식수',
        data_type=int,
    ),
    sharesFloatingRate=lw.DataDictionary(
        kor_name='유동주식비율',
        data_type=float,
    ),
    foreignSharesHolding=lw.DataDictionary(
        kor_name='외국인보유수량',
        data_type=int,
    ),
    foreignRate=lw.DataDictionary(
        kor_name='외국인보유비율',
        data_type=float,
    ),
    foreignSharesLimit=lw.DataDictionary(
        kor_name='외국인한도수량',
        data_type=int,
    ),
    foreignRateByLimit=lw.DataDictionary(
        kor_name='외국인한도소진율',
        data_type=float,
    ),

    numbersDate=lw.DataDictionary(
        kor_name='공시자료수집일',
        data_type=int,
    ),
    fiscalMonth=lw.DataDictionary(
        kor_name='실적기준일(년)',
        data_type=str,
    ),
    ifrsType=lw.DataDictionary(
        kor_name='재무기준',
        data_type=str,
    ),

    trailingSales=lw.DataDictionary(
        kor_name='4분기합산매출',
        data_type=float,
    ),
    trailingProfit=lw.DataDictionary(
        kor_name='4분기합산영업이익',
        data_type=float,
    ),
    trailingNetProfit=lw.DataDictionary(
        kor_name='4분기합산당기순이익',
        data_type=float,
    ),
    trailingProfitRate=lw.DataDictionary(
        kor_name='4분기합산기준영업이익률',
        data_type=float,
    ),
    trailingEps=lw.DataDictionary(
        kor_name='4분기합산Eps',
        data_type=float,
    ),

    yoySales=lw.DataDictionary(
        kor_name='yoy매출',
        data_type=float,
    ),
    yoyProfit=lw.DataDictionary(
        kor_name='yoy영업이익',
        data_type=float,
    ),
    yoyNetProfit=lw.DataDictionary(
        kor_name='yoy당기순이익',
        data_type=float,
    ),
    yoyProfitRate=lw.DataDictionary(
        kor_name='yoy영업이익률',
        data_type=float,
    ),
    yoyEps=lw.DataDictionary(
        kor_name='yoyEps',
        data_type=str,
    ),

    fiscalSales=lw.DataDictionary(
        kor_name='직전결산연도매출',
        data_type=float,
    ),
    fiscalSalesGrowth=lw.DataDictionary(
        kor_name='직전결산연도매출성장률',
        data_type=float,
    ),
    fiscalProfit=lw.DataDictionary(
        kor_name='직전결산연도영업이익',
        data_type=float,
    ),
    fiscalProfitRate=lw.DataDictionary(
        kor_name='직전결산연도영업이익률',
        data_type=float,
    ),
    fiscalProfitGrowth=lw.DataDictionary(
        kor_name='직전결산연도영업이익성장률',
        data_type=str,
    ),
    fiscalProfitRateGrowth=lw.DataDictionary(
        kor_name='직전결산연도영업이익률성장률',
        data_type=str,
    ),
    fiscalNetProfit=lw.DataDictionary(
        kor_name='직전결산연도당기순이익',
        data_type=float,
    ),
    fiscalNetProfitGrowth=lw.DataDictionary(
        kor_name='직전결산연도당기순이익성장률',
        data_type=float,
    ),
    fiscalAsset=lw.DataDictionary(
        kor_name='직전결산연도자산',
        data_type=float,
    ),
    fiscalAssetGrowth=lw.DataDictionary(
        kor_name='직전결산연도자산증감률',
        data_type=float,
    ),
    fiscalCapital=lw.DataDictionary(
        kor_name='직전결산연도자본',
        data_type=float,
    ),
    fiscalDebt=lw.DataDictionary(
        kor_name='직전결산연도부채',
        data_type=float,
    ),
    fiscalDebtGrowth=lw.DataDictionary(
        kor_name='직전결산연도부채증감률',
        data_type=float,
    ),
    fiscalDebtRatio=lw.DataDictionary(
        kor_name='직전결산연도부채율',
        data_type=float,
    ),
    fiscalRetentionRate=lw.DataDictionary(
        kor_name='직전결산연도유보율',
        data_type=float,
    ),
    fiscalDividendYield=lw.DataDictionary(
        kor_name='직전결산연도배당수익율',
        data_type=float,
    ),
    fiscalPayoutRatio=lw.DataDictionary(
        kor_name='직전결산연도배당성향',
        data_type=float,
    ),
    fiscalPayoutRatioGrowth=lw.DataDictionary(
        kor_name='직전결산연도배당성향증감률',
        data_type=float,
    ),
    returnOnAsset=lw.DataDictionary(
        kor_name='직전결산연도ROA',
        data_type=float,
    ),
    returnOnEquity=lw.DataDictionary(
        kor_name='직전결산연도ROE',
        data_type=float,
    ),
    fiscalEps=lw.DataDictionary(
        kor_name='직전결산연도Eps',
        data_type=float,
    ),
    fiscalEpsGrowth=lw.DataDictionary(
        kor_name='직전결산연도Eps성장률',
        data_type=float,
    ),
    fiscalPe=lw.DataDictionary(
        kor_name='직전결산연도Per',
        data_type=float,
    ),
    fiscalPriceToBook=lw.DataDictionary(
        kor_name='직전결산연도Pbr',
        data_type=float,
    ),
    fiscalDps=lw.DataDictionary(
        kor_name='직전결산연도Dps',
        data_type=float,
    ),
    fiscalDpsGrowth=lw.DataDictionary(
        kor_name='직전결산연도Dps성장률',
        data_type=float,
    ),

    forwardEps=lw.DataDictionary(
        kor_name='12개월선행Eps',
        data_type=float,
    ),
    fowardPe=lw.DataDictionary(
        kor_name='12개월선행Per',
        data_type=float,
    ),
    estimation=lw.DataDictionary(
        kor_name='컨센서스',
        data_type=float,
    ),
    estimatedMonth=lw.DataDictionary(
        kor_name='컨센서스기준일',
        data_type=str,
    ),
    targetPrice=lw.DataDictionary(
        kor_name='목표가',
        data_type=float,
    ),
    targetPricePct=lw.DataDictionary(
        kor_name='목표가대비',
        data_type=float,
    ),
    nOfEstimations=lw.DataDictionary(
        kor_name='추정기관수',
        data_type=float,
    ),
    estimatedSales=lw.DataDictionary(
        kor_name='추정매출',
        data_type=float,
    ),
    estimatedSalesGrowth=lw.DataDictionary(
        kor_name='추정매출성장률',
        data_type=float,
    ),

    estimatedProfit=lw.DataDictionary(
        kor_name='추정영업이익',
        data_type=float,
    ),
    estimatedProfitRate=lw.DataDictionary(
        kor_name='추정영업이익률',
        data_type=float,
    ),
    estimatedProfitGrowth=lw.DataDictionary(
        kor_name='추정영업이익성장률',
        data_type=str,
    ),
    estimatedProfitRateGrowth=lw.DataDictionary(
        kor_name='추정영업이익률성장률',
        data_type=float,
    ),
    estimatedNetProfit=lw.DataDictionary(
        kor_name='추정당기순이익',
        data_type=float,
    ),
    estimatedNetProfitGrowth=lw.DataDictionary(
        kor_name='추정당기순이익성장률',
        data_type=float,
    ),

    estimatedAsset=lw.DataDictionary(
        kor_name='추정자산',
        data_type=float,
    ),
    estimatedAssetGrowth=lw.DataDictionary(
        kor_name='추정자산증감률',
        data_type=float,
    ),
    estimatedDebt=lw.DataDictionary(
        kor_name='추정부채',
        data_type=float,
    ),
    estimatedDebtGrowth=lw.DataDictionary(
        kor_name='추정부채증감률',
        data_type=float,
    ),
    estimatedEps=lw.DataDictionary(
        kor_name='추정Eps',
        data_type=float,
    ),
    estimatedEpsGrowth=lw.DataDictionary(
        kor_name='추정Eps성장률',
        data_type=float,
    ),
    estimatedPe=lw.DataDictionary(
        kor_name='추정Per',
        data_type=float,
    ),
    estimatedDps=lw.DataDictionary(
        kor_name='추정Dps',
        data_type=float,
    ),
    estimatedDpsGrowth=lw.DataDictionary(
        kor_name='추정Dps성장률',
        data_type=float,
    ),
    estimatedPayoutRatio=lw.DataDictionary(
        kor_name='추정배당성향',
        data_type=float,
    ),
    estimatedPayoutRatioGrowth=lw.DataDictionary(
        kor_name='추정배당성향증감률',
        data_type=str,
    ),

    wicsDate=lw.DataDictionary(
        kor_name='WICS기준일',
        data_type=int,
    ),
    groupByMarketCap=lw.DataDictionary(
        kor_name='추종지수(대형주)',
        data_type=str,
    ),
    industryCode=lw.DataDictionary(
        kor_name='업종코드',
        data_type=str,
    ),
    industryName=lw.DataDictionary(
        kor_name='업종분류',
        data_type=str,
    ),
    sectorCode=lw.DataDictionary(
        kor_name='섹터코드',
        data_type=str,
    ),
    sectorName=lw.DataDictionary(
        kor_name='섹터분류',
        data_type=str,
    ),
    industryNameKrx=lw.DataDictionary(
        kor_name='KRX업종분류',
        data_type=str,
    ),
    industryPe=lw.DataDictionary(
        kor_name='KRX업종Pe',
        data_type=float,
    ),
    products=lw.DataDictionary(
        kor_name='주요제품',
        data_type=str,
    ),
    ipo=lw.DataDictionary(
        kor_name='상장일',
        data_type=int,
    ),

    beta=lw.DataDictionary(
        kor_name='베타',
        data_type=float,
    ),
)
